name: karbonizma
description: ""
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Service Request
  dio: ^5.7.0

  #State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.15.0

  #Page Navigation  
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
