name: karbonizma
description: ""
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Service Request
  dio: ^5.7.0

  #State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.15.0

  #Page Navigation  
  go_router: ^14.6.2

  #Local DB
  hive: ^2.2.3
  path_provider: ^2.0.14

  #Charts Animation
  gauge_indicator: ^0.4.3

  #Lottie Animation
  lottie: ^3.2.0

  #Date Time 
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/png/money.png
    - assets/png/footprint.png
    - assets/png/recycle.png